### ISSUE TITLE
customers missing when running package on test data

### ISSUE THREAD

**Issue by leinemann** [fivetran/dbt_stripe_source#19]
Hi there, I would like to run this package on our stripe prod data aswell as the test data (using the fivetran test connector).  I can override schema names accordingly.  But test customers will never be pulled in because their livemode flag will be set to false.  Would it be worth adding some configuration option to enable to run this package on test data?
Just wondering if there are some considerations that I'm not aware of?
many thanks,
Christoph.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @leinemann thanks for opening this issue!

The configuration could for sure exist to enable customer test data to run on the package. I am curious what the broader use case of using the test data is for? I am hesitant to add further configuration (especially as there is already more than I would like), but if it makes sense to apply this update for all customers then we can move forward with this feature request.

Thanks!

**Comment by leinemann** [comment]
Thank you for looking into this!  I wanted to share some context on the requirement.  Our business wants the test customers shown in a parallel but very same way as the real customers.  So for our setup we use the fivetran _test connector to get the test accounts (which all are livemode false) and then we apply this dbt package to get them into a _test analytics schema. This allows a segregated but yet like-for-like capture of test vs real customers all the way through the reporting.

**Comment by fivetran-jamie** [comment]
@leinemann i see -- so an ideal solution for you here would be to have the ability to run the package on _only_ test customers vs _only_ not-test customers, is that correct? in the [PR](https://github.com/fivetran/dbt_stripe_source/pull/22/files#diff-fd59a6ce0e9a0fddf003dfc0debab18a7211cd7016d33107dc19d2db93d5567f) i drafted, i made it so you can run on _only_ not-test customers vs test _AND_ not-test customers, which doesn't sound like what you're looking for

**Comment by leinemann** [comment]
Yes, I see it as the continuation of the ’Stripe test mode’ connector.  It writes test data into our strip_test schema and equally I would like to run the stripe dbt packages to take this test data and create the analytics  views with test data only which means that it needs to run also picking up livemode being false everywhere.  So this means I'm running my strip dbt packages twice, the second time with stripe_test being the source. 
There might be better ways of creating the test-only analytics views - please let me know.

**Comment by fivetran-jamie** [comment]
gotcha, sounds like we're on the same page then. curious -- when you run the package the second time on your test-only data, are there any other configurations you have to make to do so? like writing to a different schema, etc

**Comment by fivetran-jamie** [comment]
@leinemann this might be good to connect over in office hours! i'll be out next week but @fivetran-joemarkiewicz will be here [5tran.co/office-hours](5tran.co/office-hours)

**Comment by leinemann** [comment]
sorry about the late reply - yes, the second run for test data we run with some var overrides for the source and target schemata for the src and the other stripe package.  The office hour link returns a 404 - could you please re-paste?

**Comment by fivetran-joemarkiewicz** [comment]
Our apologies [here](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) is the proper link.

As @fivetran-jamie is OOO this week I will be helping close this Issue out. I think I am understanding @leinemann that you would be happy with a variable that simply only brings in test customers when it is configured. We can very well do that!

I did want to confirm with you that you **only** want the customer object to be filtered for test data, correct? I am aware that many other objects (charge, invoice, invoice_line, payment_intent, etc.) have a `livemode` field. Would you want only test data for these tables as well, or just customers?

Happy to chat more over office hours

**Comment by leinemann** [comment]
Hi @fivetran-joemarkiewicz, the customer object was were we first noticed the challenge but I think it would make sense to have a property applied across the board.  Let me schedule an office hour slot for the end of the week as I'm OOO as well at the moment.  
Thanks!

**Comment by fivetran-jamie** [comment]
hey @leinemann if you're still down to do your own PR lmk if you need any help! hoping to release this before our sprint ends next wednesday

**Comment by leinemann** [comment]
Hey @fivetran-jamie!  Yes, ok, great!  I've forked the repo, created a `config_livemode_cl` branch, rebased master and added other places where I think we'll need to consider livemode. I believe the structure is already so nice that the change will be limited to tmp models?  Please let me know if I'm mistaken here.  Could you let me know if this WIP PR https://github.com/leinemann/dbt_stripe_source/pull/1 against my own master is going in the right direction and if so we can finalise the naming other reviews and formalities and I can raise a proper PR against the main repo?

**Comment by leinemann** [comment]
ok, thanks @fivetran-jamie, what do you think about calling it what it is i.e. `using_livemode` and inverting the boolean.  i.e. defaulting it to true with the option of setting it to false?

**Comment by fivetran-jamie** [comment]
wahoo just pushed version 0.4.1 of the package, which includes your code @leinemann. thanks for opening the issue (and solving it 😄 )

**Comment by leinemann** [comment]
😀 thanks for your support!
