### ISSUE TITLE
FEATURE - [add metadata to customer object]

### ISSUE THREAD

**Issue by bmayer99** [fivetran/dbt_stripe_source#29]
**Are you a Fivetran customer?** 
Benoit Mayer, Stedi Inc

**Is your feature request related to a problem? Please describe.**
We store customer metadata in Stripe on the customers and would like it to flow through to reporting. the metadata is essential to our reporting.

**Describe the solution you'd like**
add metadata on customers as implemented for transactions as described https://github.com/fivetran/dbt_stripe_source/tree/v0.4.3#pivoting-out-metadata-properties

**Describe alternatives you've considered**
 

**Please indicate the level of urgency and business impact of this request** 
not critical but time sensitive. by end of month would be ideal

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [x] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this work implemented. 
- [ ] No, I'd prefer if someone else did this.  I don't have the time and/or don't know how to incorporate the changes necessary.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @bmayer99 thanks for opening this issue!

I can see this being more than doable to include the same metadata passthrough functionality to the customer staging model. I do have one quick question. You mention:

> We store customer metadata in Stripe on the customers and would like it to flow through to reporting. the metadata is essential to our reporting.

Are there specific end models within the [dbt_stripe](https://github.com/fivetran/dbt_stripe) dbt package you would expect these fields to flow downstream to? I would imagine the [stripe__customer_overview](https://github.com/fivetran/dbt_stripe/blob/master/models/stripe__customer_overview.sql) model, but curious if there are any other final models you would expect these metadata fields to be included in. Or are you only concerned about including these into your staging models to be used by your own models?

**Comment by fivetran-reneeli** [comment]
Hi @bmayer99, the Stripe package has been updated with the customer metadata passthrough functionality. Thanks for helping us improve our packages and let us know if you have questions!

**Comment by bmayer99** [comment]
thank you @fivetran-reneeli, it works great!
