### ISSUE TITLE
FEATURE - [Identifiers for multiple stripe connections]

### ISSUE THREAD

**Issue by ramiz-bozai-cerebral** [fivetran/dbt_stripe_source#33]
**Are you a Fivetran customer?** 
Yes. Ramiz Bozai, Senior Data Analyst at Cerebral

**Is your feature request related to a problem? Please describe.**
It would be great to have an identifier denoting which data/records came from which source as I union together our different stripe tables from different connections. 

**Describe the solution you'd like**
Having a column indicating what the source of the data is (like country) would allow us to filter that data based on the column.

**Describe alternatives you've considered**
This is more of a nice to have, but I understand I can possible fork this package and potentially try to add this myself.

**Additional context**
N/A

**Please indicate the level of urgency and business impact of this request** 
Not urgent. Just a nice to have feature.

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [x] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this work implemented. 
- [x] No, I'd prefer if someone else did this.  I don't have the time and/or don't know how to incorporate the changes necessary.

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for opening this feature @ramiz-bozai-cerebral! It also was great chatting with you today.

The request here would be an ideal candidate for our recent _union functionality_ feature that we have implemented in a few other packages. Essentially we have created a way in other packages for users to union data from multiple sources before the packages performs the transformations. This would mean the union ability is native to the package. 

Our team will add this to our feature request log and plan to scope this during our quarterly planning process. However, if you would like to attempt at applying this functionality yourself and open a PR, we do have supporting PRs that you could reference in the meantime! A great place to look would be our [dbt_xero_source PR](https://github.com/fivetran/dbt_xero_source/pull/11) and [dbt_xero PR](https://github.com/fivetran/dbt_xero/pull/16/files?authenticity_token=qW6gwSAKhHYDkn1gkIs97O-lH1bhkg34HK12thGk9CY3haB0ukw22VyLQKUshxL83_bItCsGkdJXZxrNYHQf6w&file-filters%5B%5D=.html&file-filters%5B%5D=.json&file-filters%5B%5D=.md) which implement this functionality. I am happy to chat through these PRs if you would like.

Thanks again for opening this, and our team will respond back once we have planned for this feature!

**Comment by dietofworms** [comment]
This would be a great feature for us at Ignition too. Keen to see it merged whenever you guys get around to it 👍

**Comment by fivetran-joemarkiewicz** [comment]
Hi All, 

I wanted to post back here and let you know that we have decided to pick this feature up in our next quarter!

**Comment by fivetran-reneeli** [comment]
Hi @ramiz-bozai-cerebral and @dietofworms! We have added the feature to allow for multiple Stripe connectors to be unioned. For more details, we've noted it in our [README](https://github.com/fivetran/dbt_stripe/blob/main/README.md#unioning-multiple-stripe-connectors). As such I will close out this issue. Let me know if you have any more questions!
