### ISSUE TITLE
Columns missing in Invoice 

### ISSUE THREAD

**Issue by lijol** [fivetran/dbt_stripe_source#50]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Missing columns 

1. PERIOD_START
2. PERIOD_END

### Describe alternatives you've considered

NA

### Are you interested in contributing this feature?

- [X] Yes.
- [X] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

### Anything else?

Can this be expedited ? This model will not be useful to me as they are important columns

**Comment by fivetran-joemarkiewicz** [comment]
@lijol thanks for opening this issue! I noticed you are open to creating a PR to incorporate these new fields. If you would like to open a PR to incorporate these fields we would be happy to review and consider folding into the package!

**Comment by lijol** [comment]
@fivetran-joemarkiewicz i will raise the PR this week

**Comment by lijol** [comment]
raised PR https://github.com/fivetran/dbt_stripe_source/pull/51

**Comment by lijol** [comment]
Added to invoice now
