### ISSUE TITLE
[Feature] Add status columns to the invoice table

### ISSUE THREAD

**Issue by lijol** [fivetran/dbt_stripe_source#53]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

The below columns to be added 
STATUS_TRANSITIONS_FINALIZED_AT
STATUS_TRANSITIONS_PAID_AT
STATUS_TRANSITIONS_VOIDED_AT
STATUS_TRANSITIONS_MARKED_UNCOLLECTIBLE_AT

### Describe alternatives you've considered

None

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by lijol** [comment]
Let me know if I can go ahead and raise PR on this change

**Comment by fivetran-reneeli** [comment]
Hi @lijol thank you for raising this ticket! We have updated the [invoice table ](https://github.com/fivetran/dbt_stripe_source/blob/main/models/stg_stripe__invoice.sql) to include these fields. As such I will close this issue!
