### ISSUE TITLE
[Bug] Uniqueness test on unique_invoice_line_item_id

### ISSUE THREAD

**Issue by lsusie** [fivetran/dbt_stripe_source#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

An error in my Fivetran/Stripe package today with uniqueness in `stg_stripe_invoice_line_items` model.
Seems to be testing for [uniqueness](https://fivetran.github.io/dbt_stripe/#!/test/test.stripe_source.unique_stg_stripe__invoice_line_item_unique_invoice_line_item_id.a59523b7b7) on `unique_invoice_line_item_id`  but I have a few records where it is not unique through the data source.

### Relevant error log or model output

```shell
17:49:29 3 of 3 START test unique_stg_stripe__invoice_line_item_unique_invoice_line_item_id  [RUN]
17:49:30 3 of 3 FAIL 3 unique_stg_stripe__invoice_line_item_unique_invoice_line_item_id . [FAIL 3 in 1.09s]
```

### Expected behavior

As this `stg_stripe_invoice_line_items` has 2 PK's I expect the `unique_stg_stripe__invoice_line_item_unique_invoice_line_item_id` to not exist.

`dbt_utils_unique_combination_of_columns_stg_stripe__invoice_line_item_invoice_line_item_id__invoice_id__source_relation` is already there to ensure the combo is unique 

### dbt Project configurations

```
  #### Variables for Fivetran/stripe package ####
  # stripe_database: database
  stripe_schema: source_ft_stripe 

  stripe__using_invoices:        True  #Disable if you are not using the invoice and invoice_line_item tables
  stripe__using_payment_method:  False  #Disable if you are not using the payment_method and payment_method_card tables
  stripe__using_subscriptions:   True  #Disable if you are not using the subscription and plan/price tables.
  stripe__using_credit_notes:    False   #Enable if you are using the credit note tables.

```

### Package versions

```
  - package: fivetran/stripe
    version: [">=0.12.0", "<0.13.0"]
```

### What database are you using dbt with?

bigquery

### dbt Version

`18:16:55 Running with dbt=1.6.11`

### Additional Context

![Screenshot 2024-04-01 at 11 21 32 AM](https://github.com/fivetran/dbt_stripe_source/assets/100633490/6185a625-b8dd-448c-81e3-4933190beb8b)

I think you just need to remove this test?

![unnamed (2)](https://github.com/fivetran/dbt_stripe_source/assets/100633490/21361e5d-cc24-409d-91bc-0c1c4ced0e5e)

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-reneeli** [comment]
Thanks @lsusie for creating this very detailed ticket! We'll look to add this fix in the coming weeks.

**Comment by fivetran-reneeli** [comment]
Hi @lsusie ! We've got the ball rolling and will work to get this released in the coming week. In the meantime, feel free to use the following branch with the update. You'll need adjust the packages.yml in your stripe package. Let me know if there are any issues!

```
  - git: https://github.com/fivetran/dbt_stripe.git
    revision: bugfix/invoice_line_item_uniqueness_test
    warn-unpinned: false

**Comment by lsusie** [comment]
@fivetran-reneeli Awesome! Thanks for all the work you and your team does!
